const allFiles = [
    {
        title: "جزوه فیزیک پایه",
        desc: "جزوه کامل فیزیک ۱ و ۲",
        category: "فیزیک",
        type: "جزوه",
        level: "دانشگاهی",
        viewUrl: "https://drive.google.com/file/d/1XKAoerWekowO56UXQ_0iw3WwX3FN0Q60/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1XKAoerWekowO56UXQ_0iw3WwX3FN0Q60",
        downloadName: "جزوه-فیزیک-پایه.pdf",
        color: "purple"
    },
    {
        title: "جزوه مبانی کامپیوتر و برنامه‌نویسی",
        desc: "جزوه کامل مبانی کامپیوتر و برنامه‌نویسی C++ — دانشگاه صنعتی بیرجند",
        category: "کامپیوتر",
        type: "جزوه",
        level: "دانشگاهی",
        viewUrl: "https://drive.google.com/file/d/15h2ylcOqKHGuvNsT1Yfdz0RezD21--jW/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=15h2ylcOqKHGuvNsT1Yfdz0RezD21--jW",
        downloadName: "جزوه-مبانی-کامپیوتر.pdf",
        color: "blue"
    },
    {
        title: "کتاب اندیشه اسلامی ۱",
        desc: "کتاب اندیشه اسلامی ۱ — آیت‌الله جعفر سبحانی و دکتر محمد محمدی",
        category: "معارف",
        type: "کتاب",
        level: "دانشگاهی",
        viewUrl: "https://drive.google.com/file/d/10TbXwsw7XGSbEHpTrzkAb9VZ1NRPWZnh/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=10TbXwsw7XGSbEHpTrzkAb9VZ1NRPWZnh",
        downloadName: "کتاب-اندیشه-اسلامی-1.pdf",
        color: "green"
    },
    {
        title: "جزوه آمار و روش تحقیق در علوم انسانی",
        desc: "جزوه اختصاصی برگ دانش — آمار، روش تحقیق، نمونه‌گیری، متغیرها، آزمون فرضیه و ...",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1GF_65KVpdGIksA0NfyAx8PPBxcFmnZ4f/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1GF_65KVpdGIksA0NfyAx8PPBxcFmnZ4f",
        downloadName: "jozve-amar-ravash-tahghigh.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی عمومی",
        desc: "جزوه اختصاصی برگ دانش — تعریف روانشناسی، مکاتب، یادگیری، حافظه، هوش، شخصیت، انگیزش، رشد و ...",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/13elZtuifvT3kRuxxgOyKrbYxpmTHVDK6/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=13elZtuifvT3kRuxxgOyKrbYxpmTHVDK6",
        downloadName: "jozve-ravanshenasi-omumi.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی رشد",
        desc: "جزوه اختصاصی برگ دانش — رشد پیش از تولد، نوزادی، کودکی، نوجوانی، بزرگسالی، سالمندی و نظریه‌های مهم رشد",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1kyHTp4611PI7_WGNJwj6nPrgkOinRKn4/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1kyHTp4611PI7_WGNJwj6nPrgkOinRKn4",
        downloadName: "jozve-ravanshenasi-roshd.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی شخصیت",
        desc: "جزوه اختصاصی برگ دانش — نظریه‌های فروید، آدلر، یونگ، اریکسون، بندورا، مازلو، راجرز و مدل پنج عامل بزرگ",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1-TsLOR5IzlbhV0z8aia9zmr1G8WK7wwH/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1-TsLOR5IzlbhV0z8aia9zmr1G8WK7wwH",
        downloadName: "jozve-ravanshenasi-shakhsiat.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی اجتماعی",
        desc: "جزوه اختصاصی برگ دانش — نگرش، نفوذ اجتماعی، همرنگی، اطاعت، گروه‌ها، رهبری، جاذبه و پیش‌داوری",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1SmpFYokvs91iATrv_ks1LBJrFcsb2QJt/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1SmpFYokvs91iATrv_ks1LBJrFcsb2QJt",
        downloadName: "jozve-ravanshenasi-ejtemaei.pdf",
        color: "purple"
    },
];