const allFiles = [
    {
        title: "جزوه فیزیک پایه",
        desc: "جزوه کامل فیزیک ۱ و ۲",
        category: "فیزیک",
        type: "جزوه",
        level: "دانشگاهی",
        viewUrl: "https://drive.google.com/file/d/1XKAoerWekowO56UXQ_0iw3WwX3FN0Q60/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1XKAoerWekowO56UXQ_0iw3WwX3FN0Q60",
        downloadName: "جزوه-فیزیک-پایه.pdf",
        color: "purple"
    },
    {
        title: "جزوه مبانی کامپیوتر و برنامه‌نویسی",
        desc: "مفاهیم پایه کامپیوتر، الگوریتم و برنامه‌نویسی C++",
        category: "کامپیوتر",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/15h2ylcOqKHGuvNsT1Yfdz0RezD21--jW/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=15h2ylcOqKHGuvNsT1Yfdz0RezD21--jW",
        downloadName: "jozve-mabani-computer.pdf",
        color: "blue"
    },
    {
        title: "کتاب اندیشه اسلامی ۱",
        desc: "کتاب مرجع اندیشه اسلامی — آیت‌الله جعفر سبحانی",
        category: "معارف",
        type: "کتاب",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/10TbXwsw7XGSbEHpTrzkAb9VZ1NRPWZnh/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=10TbXwsw7XGSbEHpTrzkAb9VZ1NRPWZnh",
        downloadName: "ketab-andishe-islami-1.pdf",
        color: "green"
    },
    {
        title: "جزوه آمار و روش تحقیق در علوم انسانی",
        desc: "آمار توصیفی، استنباطی، روش‌های تحقیق و آزمون فرضیه",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1GF_65KVpdGIksA0NfyAx8PPBxcFmnZ4f/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1GF_65KVpdGIksA0NfyAx8PPBxcFmnZ4f",
        downloadName: "jozve-amar-ravash-tahghigh.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی عمومی",
        desc: "مفاهیم پایه، مکاتب، یادگیری، حافظه، هوش و شخصیت",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/13elZtuifvT3kRuxxgOyKrbYxpmTHVDK6/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=13elZtuifvT3kRuxxgOyKrbYxpmTHVDK6",
        downloadName: "jozve-ravanshenasi-omumi.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی رشد",
        desc: "مراحل رشد انسان از تولد تا سالمندی و نظریه‌های مهم رشد",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1kyHTp4611PI7_WGNJwj6nPrgkOinRKn4/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1kyHTp4611PI7_WGNJwj6nPrgkOinRKn4",
        downloadName: "jozve-ravanshenasi-roshd.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی شخصیت",
        desc: "نظریه‌های فروید، یونگ، آدلر، مازلو، راجرز و مدل پنج عامل بزرگ",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1-TsLOR5IzlbhV0z8aia9zmr1G8WK7wwH/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1-TsLOR5IzlbhV0z8aia9zmr1G8WK7wwH",
        downloadName: "jozve-ravanshenasi-shakhsiat.pdf",
        color: "purple"
    },
    {
        title: "جزوه روانشناسی اجتماعی",
        desc: "نگرش، نفوذ اجتماعی، همرنگی، اطاعت، گروه‌ها و پیش‌داوری",
        category: "روانشناسی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1SmpFYokvs91iATrv_ks1LBJrFcsb2QJt/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1SmpFYokvs91iATrv_ks1LBJrFcsb2QJt",
        downloadName: "jozve-ravanshenasi-ejtemaei.pdf",
        color: "purple"
    },
    {
        title: "جزوه تفکر، حل مسئله و خلاقیت",
        desc: "تفکر انتقادی، تفکر خلاق، مراحل حل مسئله و پرورش خلاقیت",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1KYSK_RvPfJvTtitXfZzkyuyGbFahQ1R2/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1KYSK_RvPfJvTtitXfZzkyuyGbFahQ1R2",
        downloadName: "jozve-tafakor-hal-masale.pdf",
        color: "blue"
    },
    {
        title: "جزوه انگیزش و نقش آن در یادگیری",
        desc: "انگیزش درونی و بیرونی، خودکارآمدی و نقش معلم در افزایش انگیزه",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1gpxtW2iyurPpKk_UN0ymdsB4yfuc9lse/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1gpxtW2iyurPpKk_UN0ymdsB4yfuc9lse",
        downloadName: "jozve-angizesh-yadgiri.pdf",
        color: "green"
    },
    {
        title: "جزوه رشد و تحول در آموزش",
        desc: "ابعاد تحول، رابطه رشد و یادگیری و آموزش متناسب با سطح رشد",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1FCx0OKfAdECYAzPjvrA0nt1VVUZGkp1I/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1FCx0OKfAdECYAzPjvrA0nt1VVUZGkp1I",
        downloadName: "jozve-roshd-tahavol.pdf",
        color: "rose"
    },
    {
        title: "جزوه تفاوت‌های فردی و شناخت یادگیرندگان",
        desc: "تفاوت‌های شناختی، استعداد، سرعت یادگیری، سبک‌های یادگیری و تفاوت‌های عاطفی",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1ErLGgkEtA6shRmnx3wIXOLK1tM080eWN/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1ErLGgkEtA6shRmnx3wIXOLK1tM080eWN",
        downloadName: "jozve-tafavot-fardi.pdf",
        color: "purple"
    },
    {
        title: "جزوه حافظه و فرایندهای یادگیری",
        desc: "رمزگردانی، ذخیره‌سازی، بازیابی و روش‌های تقویت حافظه",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/140KnkfmsD7TRPIbUOWS0m1aauRoNuMfm/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=140KnkfmsD7TRPIbUOWS0m1aauRoNuMfm",
        downloadName: "jozve-hafeze.pdf",
        color: "blue"
    },
    {
        title: "جزوه مفهوم یادگیری و نظریه‌های یادگیری",
        desc: "رفتارگرایی، شناخت‌گرایی، یادگیری مشاهده‌ای و نظریه‌های پاولف، اسکینر و بندورا",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1gzztUqrD_cG9K4KbCnniVyWA2ddg0pvT/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1gzztUqrD_cG9K4KbCnniVyWA2ddg0pvT",
        downloadName: "jozve-mafhoom-yadgiri.pdf",
        color: "purple"
    },
    {
        title: "جزوه روش‌ها و فنون تدریس",
        desc: "روش‌های تدریس مستقیم، سخنرانی، پرسش و پاسخ، بحث گروهی، حل مسئله و یادگیری مشارکتی",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1p4_PvDQACtjAQ1Q_EfjDQw3jDi3t9b5q/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1p4_PvDQACtjAQ1Q_EfjDQw3jDi3t9b5q",
        downloadName: "jozve-ravesh-fonoon-tadris.pdf",
        color: "blue"
    },
    {
        title: "جزوه مبانی و مفاهیم اساسی علوم تربیتی",
        desc: "تعریف علوم تربیتی، تفاوت آموزش و تربیت، نقش معلم و یادگیرنده و عوامل مؤثر بر یادگیری",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/1ldI9Wawz27sjHvULC_kHawWS01U9Ebe-/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=1ldI9Wawz27sjHvULC_kHawWS01U9Ebe-",
        downloadName: "jozve-mabani-oloom-tarbiati.pdf",
        color: "green"
    },
    {
        title: "جزوه ارزشیابی و سنجش آموزشی",
        desc: "اندازه‌گیری، سنجش، ارزشیابی تشخیصی، تکوینی و پایانی و ابزارهای سنجش",
        category: "علوم تربیتی",
        type: "جزوه",
        level: "دانشگاهی",
        author: "جزوه اختصاصی برگ دانش",
        viewUrl: "https://drive.google.com/file/d/13wvUg5DezDmRsEKSDD7tIbuZH3FCGSJT/view",
        downloadUrl: "https://drive.google.com/uc?export=download&id=13wvUg5DezDmRsEKSDD7tIbuZH3FCGSJT",
        downloadName: "jozve-arzyabi-sanjesh.pdf",
        color: "blue"
    }
];